/**
 * Constraint types for generic type resolution.
 *
 * Constraints are generated by comparing provided argument types against
 * expected parameter types, replacing the mutable addHint/addRequirement
 * pattern in canBeAssignedTo. They are pure data — no side effects.
 *
 * Constraint kinds:
 * - 'hint': typeVar must accept this type (covariant position, e.g. argument value)
 *   Previously collected via addHint. Semantically: typeVar :> type
 * - 'requirement': typeVar must satisfy this bound (contravariant position, e.g. callback parameter)
 *   Previously collected via addRequirement. Semantically: type :> typeVar
 */

import {ok, err, type Result} from '@extra-lang/result'
import {
  type Type,
  GenericType,
  ArrayType,
  DictType,
  SetType,
  ObjectType,
  OneOfType,
  FormulaType,
  NamedEnumInstanceType,
  AnonymousEnumType,
  ClassInstanceType,
  canBeAssignedTo,
} from './types'
import type {Substitution} from './types'
import {unify} from './unification'

export type Constraint =
  | {kind: 'hint'; typeVar: GenericType; type: Type}
  | {kind: 'requirement'; typeVar: GenericType; type: Type}

/**
 * Generate constraints by walking two types in parallel — the provided type
 * (from the call site) and the expected type (from the function definition).
 *
 * Wherever a GenericType in `generics` is encountered, a constraint is emitted:
 * - Expected side is generic → 'hint' (covariant: "T must accept this type")
 * - Provided side is generic → 'requirement' (contravariant: "T must be subtype of this")
 *
 * Generics NOT in `generics` are treated as opaque/concrete types (foreign generics
 * from outer scopes).
 *
 * This is a pure function — no mutation occurs.
 */
export function generateConstraints(
  provided: Type,
  expected: Type,
  generics: Set<GenericType>,
): Constraint[] {
  if (generics.size === 0) {
    return []
  }

  const constraints: Constraint[] = []
  _generate(provided, expected, generics, constraints)
  return constraints
}

function _generate(
  provided: Type,
  expected: Type,
  generics: Set<GenericType>,
  out: Constraint[],
): void {
  // If the same type, no constraints needed
  if (provided === expected) {
    return
  }

  // Expected is a generic we're solving for → hint constraint
  if (expected instanceof GenericType && generics.has(expected)) {
    if (provided !== expected) {
      out.push({kind: 'hint', typeVar: expected, type: provided})
    }
    return
  }

  // Provided is a generic we're solving for → requirement constraint
  if (provided instanceof GenericType && generics.has(provided)) {
    if (expected !== provided) {
      out.push({kind: 'requirement', typeVar: provided, type: expected})
    }
    return
  }

  // OneOfType on the provided side: each member that can't be matched by a
  // non-generic expected member generates constraints against generic members.
  if (provided instanceof OneOfType) {
    for (const member of provided.of) {
      _generate(member, expected, generics, out)
    }
    return
  }

  // OneOfType on the expected side: if the provided type can be assigned to
  // a non-generic member, no constraints needed (the match is concrete).
  // Only generate constraints for generic members when no non-generic match exists.
  // This mirrors canBeAssignedTo's behavior of checking non-generic members first.
  if (expected instanceof OneOfType) {
    const [nonGeneric, generic] = expected.of.reduce(
      ([ng, g], member) =>
        member.hasGeneric() ? [ng, g.concat([member])] : [ng.concat([member]), g],
      [[], []] as [Type[], Type[]],
    )

    // If the provided type matches a non-generic member, no constraint needed
    if (nonGeneric.some(member => canBeAssignedTo(provided, member))) {
      return
    }

    // Otherwise, generate constraints against generic members
    for (const member of generic) {
      _generate(provided, member, generics, out)
    }
    return
  }

  // Container types — recurse into inner types
  if (provided instanceof ArrayType && expected instanceof ArrayType) {
    _generate(provided.of, expected.of, generics, out)
    return
  }

  if (provided instanceof DictType && expected instanceof DictType) {
    _generate(provided.of, expected.of, generics, out)
    return
  }

  if (provided instanceof SetType && expected instanceof SetType) {
    _generate(provided.of, expected.of, generics, out)
    return
  }

  // Object types — match props by name and position
  if (provided instanceof ObjectType && expected instanceof ObjectType) {
    for (const expectedProp of expected.props) {
      let providedType: Type | undefined
      if (expectedProp.is === 'named') {
        providedType = provided.literalAccessType(expectedProp.name)
      } else {
        const idx = expected.props.indexOf(expectedProp)
        providedType = provided.literalAccessType(idx)
      }
      if (providedType) {
        _generate(providedType, expectedProp.type, generics, out)
      }
    }
    return
  }

  // Named enum instance types — match case args
  if (
    provided instanceof NamedEnumInstanceType &&
    expected instanceof NamedEnumInstanceType
  ) {
    if (
      provided.metaType === expected.metaType &&
      provided.member.name === expected.member.name
    ) {
      for (let i = 0; i < expected.member.args.length && i < provided.member.args.length; i++) {
        _generate(provided.member.args[i].type, expected.member.args[i].type, generics, out)
      }
    }
    return
  }

  // Anonymous enum types — match case args
  if (
    provided instanceof AnonymousEnumType &&
    expected instanceof AnonymousEnumType
  ) {
    if (
      provided.metaType === expected.metaType &&
      provided.member.name === expected.member.name
    ) {
      for (let i = 0; i < expected.member.args.length && i < provided.member.args.length; i++) {
        _generate(provided.member.args[i].type, expected.member.args[i].type, generics, out)
      }
    }
    return
  }

  // Formula types — args are contravariant, return type is covariant
  if (provided instanceof FormulaType && expected instanceof FormulaType) {
    // Return type: covariant (same direction)
    _generate(provided.returnType, expected.returnType, generics, out)

    // Arguments: contravariant (flip direction)
    // When checking fn(a: Int) against fn(a: T), the expected formula's
    // parameter T needs to accept Int. But the parameter position is
    // contravariant — the expected formula's args are "provided" to the
    // actual function body. We handle this by matching args and flipping
    // the generate direction.
    //
    // Mirrors _checkFormulaArguments' short-circuit logic: when the expected
    // formula has all positional args but the provided has all named args
    // (or vice versa), match by position index.
    const expectedArgTypes = _matchFormulaArgs(expected, provided)
    for (const [expectedArgType, providedArgType] of expectedArgTypes) {
      // Flip: expected arg is "provided" to the function, provided arg is what's "expected"
      _generate(expectedArgType, providedArgType, generics, out)
    }
    return
  }

  // ClassInstanceType — match props
  if (provided instanceof ClassInstanceType && expected instanceof ClassInstanceType) {
    for (const [key, expectedType] of expected.myProps) {
      const providedType = provided.myProps.get(key)
      if (providedType) {
        _generate(providedType, expectedType, generics, out)
      }
    }
    return
  }

  // Base types / incompatible types — no constraints to generate
}

/**
 * Match the args of two FormulaTypes, producing pairs of (expectedArgType, providedArgType).
 *
 * Handles the "short circuit" case from _checkFormulaArguments: when one side
 * has all positional args and the other has all named args, match by index.
 */
function _matchFormulaArgs(
  expected: FormulaType,
  provided: FormulaType,
): [Type, Type][] {
  const pairs: [Type, Type][] = []

  // Try direct matching first (positional-to-positional, named-to-named)
  let directMatchCount = 0
  for (const expectedArg of expected.args) {
    let providedArgType: Type | undefined
    if (expectedArg.is === 'positional-argument') {
      const idx = expected.args.filter(a => a.is === 'positional-argument').indexOf(expectedArg)
      providedArgType = provided.positionalArg(idx)?.type
    } else if (expectedArg.is === 'named-argument') {
      providedArgType = provided.namedArg(expectedArg.alias)?.type
    }

    if (providedArgType) {
      pairs.push([expectedArg.type, providedArgType])
      directMatchCount++
    }
  }

  // If direct matching found results, use them
  if (directMatchCount > 0) {
    return pairs
  }

  // Short-circuit: match by index when argument styles don't align
  // (e.g., expected has all positional but provided has all named, or vice versa)
  // This mirrors _checkFormulaArguments' supportShortCircuit behavior.
  const expectedArgs = expected.args
  const providedArgs = provided.args
  const count = Math.min(expectedArgs.length, providedArgs.length)
  for (let i = 0; i < count; i++) {
    pairs.push([expectedArgs[i].type, providedArgs[i].type])
  }
  return pairs
}

/**
 * Solve a set of constraints to produce a Substitution mapping each generic
 * to a concrete type, using unification with occurs check.
 *
 * For each constraint, the type variable is unified with the constraint's type.
 * Unification uses subtype-aware logic (Int <: Float, literals <: meta types)
 * and detects infinite types via the occurs check.
 *
 * If a generic has an explicit resolvedType, all constraints are validated
 * against it, and the resolvedType is used as the binding.
 *
 * Returns Ok(Substitution) on success, or Err(errorMessage) on failure.
 */
export function solveConstraints(
  constraints: Constraint[],
  generics: GenericType[],
): Result<Substitution, string> {
  const genericsSet = new Set(generics)
  let subst: Substitution = new Map()

  // Pre-seed the substitution with explicit resolvedTypes
  for (const generic of generics) {
    if (generic.resolvedType) {
      subst.set(generic, generic.resolvedType)
    }
  }

  // Unify each constraint's typeVar with its type.
  // We call unify with the typeVar directly (not walked) so that
  // bindVar handles widening of existing bindings.
  for (const constraint of constraints) {
    const result = unify(constraint.typeVar, constraint.type, genericsSet, subst)
    if (result.isErr()) {
      return result
    }
    subst = result.get()
  }

  // Chain-resolve: walk each binding to its final value
  // (handles T → U → Int chains)
  for (const [generic] of subst) {
    let current = subst.get(generic)!
    const visited = new Set<GenericType>([generic])
    while (current instanceof GenericType && subst.has(current) && !visited.has(current)) {
      visited.add(current)
      current = subst.get(current)!
    }
    subst.set(generic, current)
  }

  // Validate bounds: after resolution, check that each generic's resolved
  // type satisfies its bound (if any). e.g. <T is Float> requires T to be
  // assignable to Float.
  for (const generic of generics) {
    if (!generic.bound) continue
    const resolved = subst.get(generic)
    if (!resolved) continue
    // Skip if resolved to another generic (bound will be checked when that generic resolves)
    if (resolved instanceof GenericType) continue

    if (!canBeAssignedTo(resolved, generic.bound)) {
      return err(
        `Type '${resolved.toCode()}' does not satisfy bound '${generic.bound.toCode()}' on generic '${generic.name}'.`,
      )
    }
  }

  return ok(subst)
}
